# Generated by Django 4.2.6 on 2023-10-11 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('internpedia', '0002_remove_internship_remote_remove_internship_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='internship',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='internpedia.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Onestar'), (2, 'Twostar'), (3, 'Threestar'), (4, 'Fourstar'), (5, 'Fivestar')], default=3),
        ),
    ]
