# Generated by Django 4.2.6 on 2023-10-12 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("internpedia", "0007_alter_review_enddate_alter_review_startdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(default="https://internpedia.com"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="location",
            field=models.CharField(default="Berkeley, CA", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="paid",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="qualifications",
            field=models.TextField(default="Alive"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="rating",
            field=models.DecimalField(decimal_places=2, default="3.0", max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="site",
            field=models.TextField(
                choices=[
                    ("On-Site", "Place1"),
                    ("Remote", "Place2"),
                    ("Hybrid", "Place3"),
                ],
                default="On-Site",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="internship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="internpedia.internship"
            ),
        ),
    ]
