# Generated by Django 4.2.6 on 2023-10-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internpedia', '0009_alter_internship_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(default='Amazon', max_length=200),
            preserve_default=False,
        ),
    ]
