# Generated by Django 4.2.6 on 2023-10-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("internpedia", "0009_alter_internship_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted", models.BooleanField(default=False)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="internpedia.review",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="review",
            name="votes",
            field=models.ManyToManyField(related_name="reviews", to="internpedia.vote"),
        ),
    ]
