# Generated by Django 4.2.6 on 2023-10-27 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("internpedia", "0010_company_title"),
        ("internpedia", "0010_vote_review_votes"),
    ]

    operations = []
