# Generated by Django 4.2.6 on 2023-11-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internpedia', '0011_merge_0010_company_title_0010_vote_review_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='site',
        ),
        migrations.AddField(
            model_name='review',
            name='hourly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='site',
            field=models.TextField(choices=[('On-Site', 'On Site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-Site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='yearly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='internpedia.internship'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='internpedia.review')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
