# Generated by Django 4.2.6 on 2023-11-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internpedia", "0012_remove_internship_qualifications_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("firstname", models.CharField(blank=True, max_length=747)),
                ("lastname", models.CharField(blank=True, max_length=747)),
                ("password", models.CharField(max_length=128, unique=True)),
                ("confirmPass", models.CharField(max_length=128, unique=True)),
                (
                    "reviews",
                    models.ManyToManyField(
                        related_name="users", to="internpedia.review"
                    ),
                ),
            ],
        ),
    ]
